branch-defaults:
  master:
    environment: rails-beanstalk-env
    group_suffix: null
global:
  application_name: PactBroker
  default_ec2_keyname: aws-eb
  default_platform: Ruby
  default_region: eu-central-1
  profile: null
  sc: git
